### ISSUE TITLE
setTextColor() function is missing in Arduino documentation

### ISSUE THREAD

**Issue by IgnacioArellano** [e-radionicacom/Inkplate-documentation#9]
Hi !
In order to get the `print()` function to actually display something on screen I have to set the text background, and text color using `display.setTextColor(BLACK, WHITE);`

I borrow the function from _Inkplate_Touchpads_ example. And notice a description is missing from documentation.

**Comment by davidzovko** [comment]
We must have missed it! @BornaBiro will add it soon

**Comment by BornaBiro** [comment]
I'm sorry for the late resoponse!

When you say it's missing a description, do you mean a description of the function or the behavior of the Inkplate? Because, setTextSize() function is not from Inkplate code, it's actually from Adafruit GFX, which documentation you can find [here](https://cdn-learn.adafruit.com/downloads/pdf/adafruit-gfx-graphics-library.pdf).
